Remove version variables as they are set in install.sh

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,13 +1,22 @@
 #!/bin/bash
 
-VERSION=1.0.1
 LTEPI_GITHUB_ID=Robotma-com/ltepi
-LTEPI_VERSION=0.9.5
 
 function assert_root {
   if [[ $EUID -ne 0 ]]; then
      echo "This script must be run as root" 
      exit 1
+  fi
+}
+
+function assert_vars {
+  if [ -z "${VERSION}" ]; then
+    echo "VERSION is missing" 
+    exit 1
+  fi
+  if [ -z "${LTEPI_VERSION}" ]; then
+    echo "LTEPI_VERSION is missing" 
+    exit 1
   fi
 }
 
@@ -25,16 +34,19 @@ function install_cli {
   install -o root -g root -D -m 644 etc/network/interfaces /etc/network/interfaces
   mv /etc/rc.local /etc/rc.local.bak
   install -o root -g root -D -m 755 etc/rc.local /etc/rc.local
+  
+  cp -f uninstall.sh /opt/inn-farm/ltepi/bin/
 }
 
 function install_ltepi {
   curl -L https://github.com/${LTEPI_GITHUB_ID}/archive/${LTEPI_VERSION}.tar.gz | tar zx
   cd ltepi-${LTEPI_VERSION}
-  ./setup
+  ./install.sh /opt/inn-farm/ltepi/bin
   cd ../
   rm -rf ltepi-${LTEPI_VERSION}
 }
 
 assert_root
+assert_vars
 install_cli
 install_ltepi
